import MainLayout from '../layouts/mainLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import InputBar from '../components/inputBar'
import {BiMoney} from "react-icons/bi"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fauxx. | Paper Trading Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className='bg-primary-background'>
          <div className='container mx-auto min-h-screen'>
            <div className='lg:flex'>
              <div className='w-full lg:w-3/5 pt-12 p-4 lg:pt-32'>
                <div className='text-4xl lg:text-6xl font-bold text-white'>Trusted and Secure Paper Trading platform</div>
                <div className='text-xl lg:text-2xl text-white my-4'>We as a secure and trusted paper trading platform want to provide our users with a user-friendly environment for trading. Our platform was established in 2018 and since than, we have been working harder everyday for the security of the trading of our users.</div>
                <div className='p-4 text-center text-2xl font-bold rounded-lg mt-12 lg:w-1/4 text-primary-background bg-primary-button'>Get Started</div>
              </div>
              <div className='w-full lg:w-2/5 pt-48 flex justify-center'>
                <div className='text-white border-2 border-white w-full m-4 lg:m-0 lg:w-3/4 rounded-lg bg-white bg-opacity-20 p-4 py-16 flex flex-col justify-center items-center'>
                  <div className='p-6 border-2 rounded-full  bg-opacity-20 -mt-40 mb-8' style={{background: "#616171"}}>
                    <BiMoney size={128} className="text-primary-button" />
                  </div>
                  <InputBar placeholder='AAPL'/>
                  <div className='my-4 w-full'>
                    <InputBar placeholder='Position Size'/>
                  </div>
                  <div className='border-b-2 w-full'></div>
                  <div className='p-3 text-center w-full text-lg font-bold rounded-lg my-4 text-primary-background bg-primary-button'>TRADE</div>

                </div>

              </div>
            </div>

            <div className='my-16 p-4'>
              <div className='text-5xl lg:w-2/4 text-primary-button font-bold'>About Us</div>
              <div className='text-white text-xl lg:w-3/4 my-4'>We&apos;re a paper trading company that is extremely safe and secure! We want to provide a platform where you can trade and buy shared based on the real stock market value with fake money in your balance. This is all for you to have an experience and learn from it! Fauxx will always be readily available to help their customers. We hope you have a great time using our platform. Happy Trading!</div>
            </div>

            <div className='lg:flex lg:space-x-8 p-4'>
              <div className='p-8 rounded-lg bg-white bg-opacity-20 w-full text-center my-4'>
                <div className='text-3xl font-bold text-white'>Safe Trade</div>
                <div className='text-xl  text-white my-5'>Our trading is extremely cautious when it comes to the security. We take extra care of the access to our databases in both the software and hardware form. Almost 87% of our active users feel completely safe in the paper trading platform we have provided to them.</div>
              </div>
              <div className='p-8 rounded-lg bg-white bg-opacity-20 w-full text-center my-4'>
                <div className='text-3xl font-bold text-white'>Customer Service</div>
                <div className='text-xl  text-white my-5'>When it comes to the customer service at Fauxx, we show no hesitation in going all the way to keep every one of our customers satisfied. Extra care is always taken to manage the customer requests and problems on time, with absolutely no delay.</div>
              </div>
              <div className='p-8 rounded-lg bg-white bg-opacity-20 w-full text-center my-4'>
                <div className='text-3xl font-bold text-white'>Real Life Model</div>
                <div className='text-xl  text-white my-5'>At Fauxx, the paper trading company is based on the real life model. This means that our stock market values are based on the ones in real life! This is an aspect that all our customers appreciate most and one we intend to continue.</div>
              </div>
            </div>


            
          </div>
          <div className='bg-secondary-background mt-8 p-4 text-center text-white text-lg'>&copy; Nabeegh Ahmed | Maha Sohail Anwer | Hassan Naeem | Hanzallah Rizwan</div>
        </div>
      </MainLayout>
    </div>
  )
}

export const getServerSideProps = async () => {
  
  
  return {
    props: {

    }
  }
}

export default Home
